version: "3"
services:
    web:
        image: "gwfvis/server:dev"
        ports:
            - "8000:80"
        volumes:
            - type: bind
              source: ./wwwroot
              target: /app/wwwroot
        depends_on:
            - db
    db:
        image: "mysql:5"
        environment:
            MYSQL_ROOT_PASSWORD: "123456qaz"
        volumes:
            - ./sql_init:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
            - "33060:33060"