version: "3.2"
services:
    client:
        image: "gwfvis/client:dev"
        ports:
            - "8000:80"
        depends_on:
            - server
    server:
        image: "gwfvis/server:dev"
        ports:
            - "8001:80"
        volumes:
            - type: bind
              source: ./wwwroot
              target: /app/wwwroot
        depends_on:
            - db
    db:
        image: "mysql:5"
        environment:
            MYSQL_ROOT_PASSWORD: "123456qaz"
        volumes:
            - "./sql_init:/docker-entrypoint-initdb.d"
        ports:
            - "3306:3306"
            - "33060:33060"